name: "3.8"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    network_mode: service:db
    volumes:
    - ../..:/workspaces:cached
    command: ["sleep", "infinity"]
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
    - db-data:/var/lib/mysql
    - ../scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: jimu
      MYSQL_DATABASE: jimu
volumes:
  db-data:
